### ISSUE TITLE
[1.12.2] crash

### ISSUE THREAD

**Issue by jonqrandom** [talandar/ProgressiveDifficulty#5]
given the behaviour i'm seeing it's probably a mod conflict, but i'm not seeing anything useful in the logs, it crashes directly after buffing a different (and usually vanilla) mob each time, here's the [crash](https://hastebin.com/urecixarez) and fml-latest ([part 1](https://paste.ee/p/PGRdE) and [part 2](https://paste.ee/p/iA5zH)) logs.

other than "keep swapping mods in and out until something changes", is there anything smarter i can do on my end to provide better data?

EDIT: setting B:DifficultyControlEnabled=false causes [this crash](https://paste.ee/p/XVdn9) immediately after world load, even of a newly created world that's never had this mod running in it.

**Comment by talandar** [comment]
Thanks for the well-documented, well formatted bug report.  I'll look into it as soon as I get a chance.

**Comment by talandar** [comment]
This should be fixed with version 3.1.  Once curseforge approves it, please check it out and let me know if it fixed your issues.

**Comment by jonqrandom** [comment]
hey, thank _you_, i've given it a good couple of hours at least, bimbled back and forth to the nether etc, everything is fine now (including the B:DifficultyControlEnabled=false, too) :)
