### ISSUE TITLE
[1.12.2] Better Questing

### ISSUE THREAD

**Issue by teagan75** [talandar/ProgressiveDifficulty#9]
I see no new reward with Better Questing installed with your mod. 

mc version: 1.12.2
Forge version: 14..23.5.2854
Progressive difficulty: 3.1
Better Questing: 3.5.329

**Comment by talandar** [comment]
Sorry, the documentation is definitely unclear.  I do not have integration with better questing in the 1.12 version of the mod, only 1.11.  I upgraded the wiki to make that explicit.
